# travis-ci settings
# https://docs.travis-ci.com/user/languages/r/

os: linux
dist: bionic
latex: false
warnings_are_errors: false

apt_packages:
 - libxml2-dev
 - libssl-dev
 - libcurl4-openssl-dev
 - libudunits2-dev
 - libopenblas-base
 - pandoc

language: r
r: 3.6.0

repos:
 CRAN: https://cloud.r-project.org

cache:
    packages: true

git:
 depth: 3

branches:
 only: 
  - master
  - twoday

script:
 - chmod +x deploy.sh
 - bash deploy.sh

